# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62e154270217e3c513af3cb4973897defdb551751597e69e7785923082afcb2480af56f233f21152994aa858874add02af5e182d146aca43fb437164bd716c82

test:
  secret_key_base: 63fc25b3248d95b1f9cc36eeaa75daf44044531fa9eb07c83603349ad6eef8230f5ce40880dc8a754b92c95c4f23860f0976d12c0ebed2d44b184c16a596607e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
